version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wptrupayers
      MYSQL_USER: spinit
      MYSQL_PASSWORD: spinit
    networks:
      - trupayers

  wp:
    depends_on:
      - db
    build: ./
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: spinit
      WORDPRESS_DB_PASSWORD: spinit
      WORDPRESS_DB_NAME: wptrupayers
    networks:
      - trupayers

  cli:
    image: wordpress:cli
    volumes:
      - ./wp:/var/www/html/
    networks:
      - trupayers

  # react:
  #   stdin_open: true
  #   depends_on:
  #     - wp
  #   build: .
  #   volumes:
  #     - ./wp/wp-content/plugins/trupayers-signup/trupayers-signup-react/public:/app/public
  #     - ./wp/wp-content/plugins/trupayers-signup/trupayers-signup-react/build:/app/build
  #     - ./wp/wp-content/plugins/trupayers-signup/trupayers-signup-react/:/app
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - trupayers

networks:
  trupayers:
volumes:
  db_data: {}
